regions:
- eu-west-1
- global

account-blocklist:
- "211125308792"
- "919717595318"
- "841162688055"
- "423623844928"
- "440388274549"
- "024100176592"

accounts:
  244446109198:
    filters:
      IAMUser:
      - "iamadmin"
      - "iamadminjs"
      IAMUserPolicyAttachment:
      - "iamadmin -> AdministratorAccess"
      - "iamadminjs -> AdministratorAccess"
      - "iamadminjs -> IAMUserChangePassword "
      IAMUserAccessKey:
      - "iamadmin -> AKIATR2Q7TYHACGCUWV7"
      - "iamadminjs -> AKIATR2Q7TYHEDWWRCMI"
  "423623844928": {}
  "841162688055": {}
  "147997127509": {}
  "474668387623": {}

resource-types:
  excludes:
  - Route53HostedZone
