---
AWSTemplateFormatVersion: 2010-09-09
Description: Adds another bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketName: !Sub 'aws-accelerator-add-another-bucket-${AWS::AccountId}-${AWS::Region}'      
      