customizations:
  cloudFormationStackSets: []
  cloudFormationStacks:
    - name: !Sub 'AWSAccelerator-Add-Another-Bucket-Stack-${AWS::AccountId}-${AWS::Region}'
      description: Adds yet another bucket
      regions:
        - us-east-1
      deploymentTargets:
        organizationalUnits:
          - Root
      runOrder: 1
      template: ./cfn-templates/s3-adder.yaml
      terminationProtection: true
