customizations:
  cloudFormationStackSets: []
  cloudFormationStacks:
    - name: Add-Another-Bucket-Stack
      description: Adds yet another bucket
      regions:
        - us-east-1
      deploymentTargets:
        organizationalUnits:
          - Root
      runOrder: 1
      template: ./cfn-templates/s3-adder.yaml
      terminationProtection: true
