##################################################################################################################
# For additional configurable services, features, and property descriptions,                                     #
# please review our network configuration reference in our README.md:                                            #
# https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.SecurityConfig.html  #
##################################################################################################################

homeRegion: &HOME_REGION us-east-1
centralSecurityServices:
  ##################################################################################################################
  # Based upon AWS Security Reference Architecture (AWS SRA),                                                      #
  # Assigning delegated administrator to security tooling (Audit) account                                          #
  # https://docs.aws.amazon.com/prescriptive-guidance/latest/security-reference-architecture/security-tooling.html #
  ##################################################################################################################
  delegatedAdminAccount: Audit
  ebsDefaultVolumeEncryption:
    enable: true
    excludeRegions: []
  s3PublicAccessBlock:
    enable: true
    excludeAccounts: []
  scpRevertChangesConfig:
    enable: true
    snsTopicName: Security
  macie:
    enable: true
    excludeRegions: []
    policyFindingsPublishingFrequency: FIFTEEN_MINUTES
    publishSensitiveDataFindings: true
  guardduty:
    enable: true
    excludeRegions: []
    s3Protection:
      enable: true
      excludeRegions: []
    exportConfiguration:
      enable: true
      overrideExisting: true
      destinationType: S3
      exportFrequency: FIFTEEN_MINUTES
  auditManager:
    enable: true
    excludeRegions: []
    defaultReportsConfiguration:
      enable: true
      destinationType: S3
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 1000
        noncurrentVersionExpiration: 1000
  detective:
    enable: false
    excludeRegions: []
  ##################################################################################################################
  # AWS Security Hub Configurations                                                                                #
  ##################################################################################################################
  securityHub:
    enable: true
    regionAggregation: true
    excludeRegions: []
    standards:
      #############################################################################################################
      # Enable AWS Security Hub standards based upon a customer specific requirements                             #
      # For the standard configuration, we have enabled the following standards:                                          #
      # - AWS Foundational Security Best Practices (FSBP)                                                         #
      # - Center for Internet Security (CIS) AWS Foundations Benchmark v1.4.0                                     #
      # - National Institute of Standards and Technology (NIST) SP 800-53 Rev. 5                                  #                                                                                                       #
      # Controls that you might want to disable based upon Security Hub recommendation                            #
      # https://docs.aws.amazon.com/securityhub/latest/userguide/controls-to-disable.html                         #
      #############################################################################################################
      - name: AWS Foundational Security Best Practices v1.0.0
        # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html
        enable: true
      - name: CIS AWS Foundations Benchmark v1.4.0
        # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html
        enable: true
      - name: NIST Special Publication 800-53 Revision 5
        # https://docs.aws.amazon.com/securityhub/latest/userguide/nist-standard.html
        enable: true
  ssmAutomation:
    excludeRegions: []
    documentSets: []
accessAnalyzer:
  enable: true
iamPasswordPolicy:
  allowUsersToChangePassword: true
  hardExpiry: false
  requireUppercaseCharacters: true
  requireLowercaseCharacters: true
  requireSymbols: true
  requireNumbers: true
  minimumPasswordLength: 14
  passwordReusePrevention: 24
  maxPasswordAge: 90
awsConfig:
  enableConfigurationRecorder: true
  enableDeliveryChannel: true
  ruleSets:
    - deploymentTargets:
        organizationalUnits:
          - Root
      rules:
        #############################################################################
        # Enabling additional config rules not implemented through AWS Security Hub #
        #############################################################################
        - name: accelerator-iam-user-group-membership-check
          complianceResourceTypes:
            - AWS::IAM::User
          identifier: IAM_USER_GROUP_MEMBERSHIP_CHECK
        - name: accelerator-securityhub-enabled
          identifier: SECURITYHUB_ENABLED
        - name: accelerator-cloudtrail-enabled
          identifier: CLOUD_TRAIL_ENABLED
        - name: accelerator-cloudtrail-s3-dataevents-enabled
          identifier: CLOUDTRAIL_S3_DATAEVENTS_ENABLED
        - name: accelerator-emr-kerberos-enabled
          identifier: EMR_KERBEROS_ENABLED
        - name: accelerator-iam-group-has-users-check
          complianceResourceTypes:
            - AWS::IAM::Group
          identifier: IAM_GROUP_HAS_USERS_CHECK
        - name: accelerator-s3-bucket-policy-grantee-check
          complianceResourceTypes:
            - AWS::S3::Bucket
          identifier: S3_BUCKET_POLICY_GRANTEE_CHECK
        # Note, included in Security Hub AFBP slightly different with ports 80 and 443
        - name: accelerator-internet-gateway-authorized-vpc-only
          complianceResourceTypes:
            - AWS::EC2::InternetGateway
          identifier: INTERNET_GATEWAY_AUTHORIZED_VPC_ONLY
        - name: accelerator-iam-no-inline-policy-check
          complianceResourceTypes:
            - AWS::IAM::User
            - AWS::IAM::Role
            - AWS::IAM::Group
          identifier: IAM_NO_INLINE_POLICY_CHECK
        - name: accelerator-cloudwatch-log-group-encrypted
          identifier: CLOUDWATCH_LOG_GROUP_ENCRYPTED
        - name: accelerator-ec2-instance-detailed-monitoring-enabled
          complianceResourceTypes:
            - AWS::EC2::Instance
          identifier: EC2_INSTANCE_DETAILED_MONITORING_ENABLED
        - name: accelerator-ec2-volume-inuse-check
          inputParameters:
            deleteOnTermination: "TRUE"
          complianceResourceTypes:
            - AWS::EC2::Volume
          identifier: EC2_VOLUME_INUSE_CHECK
        - name: accelerator-cloudtrail-security-trail-enabled
          identifier: CLOUDTRAIL_SECURITY_TRAIL_ENABLED
        - name: accelerator-guardduty-non-archived-findings
          inputParameters:
            daysHighSev: "1"
            daysLowSev: "30"
            daysMediumSev: "7"
          identifier: GUARDDUTY_NON_ARCHIVED_FINDINGS
        - name: accelerator-sagemaker-endpoint-configuration-kms-key-configured
          identifier: SAGEMAKER_ENDPOINT_CONFIGURATION_KMS_KEY_CONFIGURED
        - name: accelerator-sagemaker-notebook-instance-kms-key-configured
          identifier: SAGEMAKER_NOTEBOOK_INSTANCE_KMS_KEY_CONFIGURED
        - name: accelerator-dynamodb-table-encrypted-kms
          complianceResourceTypes:
            - AWS::DynamoDB::Table
          identifier: DYNAMODB_TABLE_ENCRYPTED_KMS

        # NIST 800-53-rev5 Conformance Pack - Additional 15
        - name: accelerator-account-part-of-organizations
          identifier: ACCOUNT_PART_OF_ORGANIZATIONS
        - name: accelerator-codebuild-project-artifact-encryption
          complianceResourceTypes:
            - AWS::CodeBuild::Project
          identifier: CODEBUILD_PROJECT_ARTIFACT_ENCRYPTION
        - name: accelerator-dynamodb-throughput-limit-check
          identifier: DYNAMODB_THROUGHPUT_LIMIT_CHECK
        - name: accelerator-ebs-optimized-instance
          complianceResourceTypes:
            - AWS::EC2::Instance
          identifier: EBS_OPTIMIZED_INSTANCE
        - name: accelerator-lambda-dlq-check
          complianceResourceTypes:
            - AWS::Lambda::Function
          identifier: LAMBDA_DLQ_CHECK
        - name: accelerator-no-unrestricted-route-to-igw
          complianceResourceTypes:
            - AWS::EC2::RouteTable
          identifier: NO_UNRESTRICTED_ROUTE_TO_IGW
        - name: accelerator-secretsmanager-using-cmk
          complianceResourceTypes:
            - AWS::SecretsManager::Secret
          identifier: SECRETSMANAGER_USING_CMK

    # Optional Config rules to check for resources protected by backups.
    - deploymentTargets:
        organizationalUnits: []
      rules:
        - name: accelerator-aurora-resources-protected-by-backup-plan
          complianceResourceTypes:
            - AWS::RDS::DBCluster
          identifier: AURORA_RESOURCES_PROTECTED_BY_BACKUP_PLAN
        - name: accelerator-backup-plan-min-frequency-and-min-retention-check
          complianceResourceTypes:
            - AWS::Backup::BackupPlan
          identifier: BACKUP_PLAN_MIN_FREQUENCY_AND_MIN_RETENTION_CHECK
        - name: accelerator-backup-recovery-point-encrypted
          complianceResourceTypes:
            - AWS::Backup::RecoveryPoint
          identifier: BACKUP_RECOVERY_POINT_ENCRYPTED
        - name: accelerator-backup-recovery-point-manual-deletion-disabled
          complianceResourceTypes:
            - AWS::Backup::BackupVault
          identifier: BACKUP_RECOVERY_POINT_MANUAL_DELETION_DISABLED
        - name: accelerator-ec2-resources-protected-by-backup-plan
          complianceResourceTypes:
            - AWS::EC2::Instance
          identifier: EC2_RESOURCES_PROTECTED_BY_BACKUP_PLAN
cloudWatch:
  metricSets: []
  alarmSets: []
keyManagementService:
  keySets: []